import type { Metadata } from "next";
import "./ui/globals.css";
import Sidebar from "@/app/ui/layout/sidebar/sidebar";
import Navbar from "@/app/ui/layout/navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body className="bg-white dark:bg-black text-black dark:text-white antialiased">
    <div className="flex">
      <Sidebar/>
      <div className="flex-1">
        <Navbar/>
        <div className="px-5 pb-5">
          {children}
        </div>
      </div>
    </div>
    </body>
    </html>
  );
}
